### ISSUE TITLE
compute_dataset_iou error

### ISSUE THREAD

**Issue by panovr** [mrsebai/aerial-tile-segmentation#1]
Hi, I have changed `BATCH_SIZE  = 9`, and train the model. When I run the code `compute_dataset_iou(model, valid_ds, VALID_STEPS_PER_EPOCH)`, there was an error:

```
---------------------------------------------------------------------------
InvalidArgumentError                      Traceback (most recent call last)
Input In [263], in <cell line: 2>()
      1 # Iterate over the whole dataset and output the confusion matrix and per class IOU
----> 2 compute_dataset_iou(model, valid_ds, VALID_STEPS_PER_EPOCH)

Input In [262], in compute_dataset_iou(model, ds, steps)
      2 def compute_dataset_iou(model, ds, steps):
----> 3     total_cm = compute_dataset_cm(model, ds, steps)
      4     normalized_cm = total_cm / tf.reduce_sum(total_cm, axis=1, keepdims=True)
      5     sum_over_row = tf.reduce_sum(total_cm, axis=0)

Input In [261], in compute_dataset_cm(model, ds, steps, normalize)
      7     pred = tf.argmax(pred, axis=-1, output_type=tf.int32)
      8     label = patch_pairs[1]
----> 9     total_cm += tf.math.confusion_matrix(tf.reshape(label, [-1]), tf.reshape(pred, [-1]))
     10 # normalizing the confusing matrix
     11 if normalize: 

File ~/anaconda3/envs/airbus/lib/python3.9/site-packages/tensorflow/python/util/traceback_utils.py:153, in filter_traceback.<locals>.error_handler(*args, **kwargs)
    151 except Exception as e:
    152   filtered_tb = _process_traceback_frames(e.__traceback__)
--> 153   raise e.with_traceback(filtered_tb) from None
    154 finally:
    155   del filtered_tb

File ~/anaconda3/envs/airbus/lib/python3.9/site-packages/tensorflow/python/framework/ops.py:7186, in raise_from_not_ok_status(e, name)
   7184 def raise_from_not_ok_status(e, name):
   7185   e.message += (" name: " + name if name is not None else "")
-> 7186   raise core._status_to_exception(e) from None

InvalidArgumentError: Incompatible shapes: [6,6] vs. [5,5] [Op:AddV2]
​
```

I found that in one batch, there will be confusion matrix shape as [5,5], but total_cm shape is [6,6], they did't match. Maybe in this batch, the patch image lack of one class.

```
tf.Tensor(
[[  3846      3 158742   5137      0]
 [     0      0      0      0      0]
 [    80      6   9529    176   1924]
 [ 12928      0 135083 121233 102881]
 [     0      0      0   1061  37195]], shape=(5, 5), dtype=int32)
```

**Comment by mrsebai** [comment]
Hello Yili
Thanks for your interest in my project. Unfortunately it's been a while I am not active in this project.
The only suggestion I might give to try bigger batch size, and ideally in the power of 2 order, it makes the internals of tensorflow work smoother.
I started from scratch and highly encourage you also to do so, harder but way more rewarding.
All the best Yili

Téléchargez Outlook pour iOS<https://aka.ms/o0ukef>
________________________________
De : Yili Zhao ***@***.***>
Envoyé : Tuesday, April 5, 2022 2:48:39 PM
À : mrsebai/aerial-tile-segmentation ***@***.***>
Cc : Subscribed ***@***.***>
Objet : [mrsebai/aerial-tile-segmentation] compute_dataset_iou error (Issue #1)


Hi, I have changed BATCH_SIZE = 9, and train the model. When I run the code compute_dataset_iou(model, valid_ds, VALID_STEPS_PER_EPOCH), there was an error:

---------------------------------------------------------------------------

InvalidArgumentError                      Traceback (most recent call last)

Input In [263], in <cell line: 2>()

      1 # Iterate over the whole dataset and output the confusion matrix and per class IOU

----> 2 compute_dataset_iou(model, valid_ds, VALID_STEPS_PER_EPOCH)



Input In [262], in compute_dataset_iou(model, ds, steps)

      2 def compute_dataset_iou(model, ds, steps):

----> 3     total_cm = compute_dataset_cm(model, ds, steps)

      4     normalized_cm = total_cm / tf.reduce_sum(total_cm, axis=1, keepdims=True)

      5     sum_over_row = tf.reduce_sum(total_cm, axis=0)



Input In [261], in compute_dataset_cm(model, ds, steps, normalize)

      7     pred = tf.argmax(pred, axis=-1, output_type=tf.int32)

      8     label = patch_pairs[1]

----> 9     total_cm += tf.math.confusion_matrix(tf.reshape(label, [-1]), tf.reshape(pred, [-1]))

     10 # normalizing the confusing matrix

     11 if normalize:



File ~/anaconda3/envs/airbus/lib/python3.9/site-packages/tensorflow/python/util/traceback_utils.py:153, in filter_traceback.<locals>.error_handler(*args, **kwargs)

    151 except Exception as e:

    152   filtered_tb = _process_traceback_frames(e.__traceback__)

--> 153   raise e.with_traceback(filtered_tb) from None

    154 finally:

    155   del filtered_tb



File ~/anaconda3/envs/airbus/lib/python3.9/site-packages/tensorflow/python/framework/ops.py:7186, in raise_from_not_ok_status(e, name)

   7184 def raise_from_not_ok_status(e, name):

   7185   e.message += (" name: " + name if name is not None else "")

-> 7186   raise core._status_to_exception(e) from None



InvalidArgumentError: Incompatible shapes: [6,6] vs. [5,5] [Op:AddV2]

​

**Comment by panovr** [comment]
Yes, I also think bigger batch size will reduce or eliminate this error. Thanks!
